### ISSUE TITLE
payload creation

### ISSUE THREAD

**Issue by pubeosp54332** [Mr-Un1k0d3r/ThunderShell#12]
how does one create a payload, the current structure is not working

**Comment by Mr-Un1k0d3r** [comment]
Can you elaborate a bit more? both the powershell and exe work perfectly on my side. I'm suspecting that you may be fetching the payload by hand instead of remotely downloading it. I will had a raw type that add the proper newline

**Comment by pubeosp54332** [comment]
I even downloaded and it dint work or load anything..

**Comment by pubeosp54332** [comment]
i followed all the instructions on the page...or am i the one doing it wrongly....
http://my ip:1111/cat.png...
from there it got stuck...

**Comment by pubeosp54332** [comment]
or how do i generate the payload.... and the method of payload delivery.

i might be doing it wrongly

**Comment by Mr-Un1k0d3r** [comment]
make sure you do a git pull first since I made some changes last night. Then can you try the exe payload (make sure mono-dmcs  is installed)

The exe can be fetch using the http://url/cat.png/exe/

if this one is working (the purpose is to make sure that the listener is setup properly) I will try to see what's the issue with the powershell on your end

**Comment by pubeosp54332** [comment]
Trying it out

**Comment by pubeosp54332** [comment]
![error](https://user-images.githubusercontent.com/40981639/49949901-d351af80-ff07-11e8-9231-524d22132b2b.png)

getting tht error

**Comment by Mr-Un1k0d3r** [comment]
it's not an error it's the actually exe. I should maybe set the http header to force the download prompt :)

also based on the string it seems like the fqdn is not good http://:1111 is point pointing to localhost is the expected behavior?

For the PowerShell I found the issue when used with IEX working on the fix.

**Comment by pubeosp54332** [comment]
ok,
now whn i run the download command..the payload doesnt give a shell..and my listener is well set no shell spawns on my end.
![error2](https://user-images.githubusercontent.com/40981639/49955099-0d747e80-ff13-11e8-8c0c-6c34bca4d034.png)

i get this

**Comment by Mr-Un1k0d3r** [comment]
Seems like you are trying to run the exe through powershell.

I've update the code to force the exe download so if you use http://url/cat.png/exe/ you should be prompted to download the exe directly. You can then run it.

**Comment by pubeosp54332** [comment]
Let. Me see.. Have u fixed the powershell

**Comment by Mr-Un1k0d3r** [comment]
working on it

**Comment by secdb** [comment]
"http://:1111" probably throw that error
