### ISSUE TITLE
python syntax and payload generation

### ISSUE THREAD

**Issue by pasoles** [Mr-Un1k0d3r/ThunderShell#19]
Hello

I was running version 2.0.2 and I upgraded to the latest version and I have some issues. 
When I tried to start the application I got a python syntax error in core/gui.py "TypeError: __init__() got an unexpected keyword argument 'static_path'". I completely removed the static_path argument and the server started.

Also the generated payloads are always pointing to http://1.1.1.1:1111

thanks

**Comment by SkiddieTech** [comment]
Also getting the 'static_path' error from latest version, removing it from /core/gui.py solved the problem.

**Comment by jasc22** [comment]
Hi Mr_Unik0d3r, I'm getting a similar issue as SkiddieTech. I removed static_path which start ThunderShell but get the following error with Redis. Does not appear to be starting Redis. I'm running this on Kali Rolling.
[-] Failed to connect to the redis instance

Thanks!

**Comment by Mr-Un1k0d3r** [comment]
Regarding the redis instance on top of my head there is two options:

redis is not started issuing the following command may help:  service redis-server start
kali have sometime outdated package and the connector may not be compatible I personally use debian and ubuntu as my development platform.

I'm currently setting up a kali VM to check if the root cause is kali package version.

**Comment by Mr-Un1k0d3r** [comment]
we also figured the static_path issue once again kali repo is to blame. Their version is different. we will add a fail check that will use static_folder instead of static_path for kali user

**Comment by Mr-Un1k0d3r** [comment]
we addresse both redis and flask variable for kali by forcing the service to be started everytime thundershell is launched. A test case was also added to prevent the flask error on kali
